### PR TITLE
feat: run tests in headless mode

### LINKED ISSUE #706: Run tests in headless mode for CI
Currently tests are being run in interactive mode rather than headless as headless mode hides the browser and provide better visibility throughout the logs rather than the interactive mode.

### PR DESCRIPTION
**Pull request by meenal06**
Signed-off-by: Meenal Trivedi <meenaltrivedi6102@gmail.com>

This text can be deleted when you are ready to make the pull request: 

For each PR, please add the following, if appropriate: 

- fixes #706
- see CI logs
- checkout on local and run `npm test`

### CODE REVIEW

**Comment by meenal06** [comment]
Hi @uosl , please do take a look !

**Comment by meenal06** [comment]
@uosl , what version of node.js is being used in the CircleCI? As cypress support Node v8 and greater/

**Comment by heralden** [comment]
It uses the machine executor ubuntu-1604:201903-01 which probably has an older Node version. I'll create a PR to upgrade to ubuntu-2004:202010-01.

**Comment by meenal06** [comment]
Hi @uosl , please do take a look. All green ✅

**Review by heralden — APPROVED** [review]
Good to see green again! Thanks for updating the CI script.

**Pull request merged**
